export default {
  eth: {
    default: false,
    network: 'mainnet',
    networkId: 1,
    chainId: 1,
    chainName: 'Ethereum Mainnet',
    chainSymbol: 'eth',
    decimals: 18,
    logo: '',
    rpcUrl: 'https://mainnet.infura.io/v3/47a7711b802c486787db98828b250cea',
  },
  goerli: {
    default: true,
    network: 'goerli',
    networkId: 5,
    chainId: 5,
    chainName: 'goerli',
    chainSymbol: 'goerli',
    decimals: 18,
    logo: '',
    rpcUrl: 'https://goerli.infura.io/v3/47a7711b802c486787db98828b250cea',
  },
  ganache: {
    default: false,
    network: 'Rinkeby',
    networkId: 5777,
    chainId: 4,
    chainName: 'Rinkeby',
    chainSymbol: 'Rinkeby',
    decimals: 18,
    logo: '',
    rpcUrl: 'https://rinkeby.infura.io/v3/2E9uELwfFcEKt73FOGQEsAEfCrv',
  },
}
